### List favorites
GET http://localhost:5092/api/favorites
Authorization: Bearer <token>

### Delete one
DELETE http://localhost:5092/api/favorites/14
Authorization: Bearer <token>

### Delete one
DELETE http://localhost:5092/api/favorites/13
Authorization: Bearer <token>

### List again
GET http://localhost:5092/api/favorites
Authorization: Bearer <token>
